#!/bin/bash

# Scanning for USB and Bluetooth devices
echo "Scanning for USB and Bluetooth devices..."

CHECKLIST_ARGS=()

# Iterate through all detected USB device paths in sysfs
for syspath in /sys/bus/usb/devices/*; do
    # Check if it is an actual device endpoint
    if [ -f "$syspath/idProduct" ] && [ -f "$syspath/idVendor" ]; then
        dev_path=$(basename "$syspath")
        
        # Skip root hubs (e.g., usb1, usb2) to keep the menu uncluttered
        if [[ "$dev_path" == usb* ]]; then
            continue
        fi

        # Extract manufacturer and product names for the GUI
        product="Unknown Device"
        manufacturer=""
        [ -f "$syspath/product" ] && product=$(cat "$syspath/product")
        [ -f "$syspath/manufacturer" ] && manufacturer=$(cat "$syspath/manufacturer")
        
        label="Port $dev_path: $manufacturer $product"
        
        # Check current wake-up status to pre-fill the checkboxes accurately
        status="off"
        if [ -f "$syspath/power/wakeup" ]; then
            current_wakeup=$(cat "$syspath/power/wakeup")
            if [ "$current_wakeup" == "enabled" ]; then
                status="on"
            fi
        fi
        
        CHECKLIST_ARGS+=("$dev_path" "$label" "$status")
    fi
done

if [ ${#CHECKLIST_ARGS[@]} -eq 0 ]; then
    echo "No USB devices found."
    exit 1
fi

# Launch kdialog checklist
SELECTED=$(kdialog --title "USB/Bluetooth Wake Configuration" \
                   --checklist "Select devices to allow them to wake the system:" \
                   "${CHECKLIST_ARGS[@]}")

# Exit cleanly if the user closes the window or clicks Cancel
if [ $? -ne 0 ]; then
    echo "Operation cancelled."
    exit 0
fi

# Set up the target rules file and a temporary file for writing
RULE_FILE="/etc/udev/rules.d/20-usb-wakeup-gui.rules"
TEMP_FILE=$(mktemp)

echo "# Generated by USB Wake-up GUI Tool" > "$TEMP_FILE"

# Remove quotes from kdialog output and iterate through selected ports
if [ -n "$SELECTED" ]; then
    CLEANED_SELECTION=$(echo "$SELECTED" | tr -d '"')
    
    for dev in $CLEANED_SELECTION; do
        echo "ACTION==\"add|bind\", SUBSYSTEM==\"usb\", KERNEL==\"$dev\", ATTR{power/wakeup}=\"enabled\"" >> "$TEMP_FILE"
    done
    echo "Devices selected. Applying rules..."
else
    echo "# No devices selected. Rules cleared." >> "$TEMP_FILE"
    echo "No devices selected. Clearing previous rules..."
fi

# Escalate privileges specifically for applying the system changes
# This will prompt you for your password in the terminal!
sudo cp "$TEMP_FILE" "$RULE_FILE"
sudo chmod 644 "$RULE_FILE"
rm "$TEMP_FILE"

sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Configuration applied successfully!"
